### PR TITLE
switch to office-toolbox in quick start

### PR DESCRIPTION
**Pull request by hongbo-miao**
Moved old quick start in OLD folder.

**Note the office-toolbox link needs to be updated in the future when we publish.**

### CODE REVIEW

**Comment by Lauragra** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[LauragraDocset0317235153/excel/excel-add-ins-get-started-angular.md](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/excel-add-ins-get-started-angular.md) | :warning:Warning | | [Details](#user-content-LauragraDocset0317235153%2Fexcel%2Fexcel-add-ins-get-started-angular.md)
[LauragraDocset0317235153/excel/excel-add-ins-get-started-react.md](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/excel-add-ins-get-started-react.md) | :warning:Warning | | [Details](#user-content-LauragraDocset0317235153%2Fexcel%2Fexcel-add-ins-get-started-react.md)
[LauragraDocset0317235153/excel/OLD/excel-add-ins-get-started-angular.md](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/OLD/excel-add-ins-get-started-angular.md) | :white_check_mark:Succeeded | |
[LauragraDocset0317235153/excel/OLD/excel-add-ins-get-started-react.md](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/OLD/excel-add-ins-get-started-react.md) | :white_check_mark:Succeeded | |
[LauragraDocset0317235153/excel/OLD/images/excel-online-upload.png](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/OLD/images/excel-online-upload.png) | :white_check_mark:Succeeded | |
[LauragraDocset0317235153/excel/OLD/images/yo-office.png](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/OLD/images/yo-office.png) | :white_check_mark:Succeeded | |
[LauragraDocset0317235153/excel/images/office-toolbox-generate.png](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/images/office-toolbox-generate.png) | :white_check_mark:Succeeded | |
[LauragraDocset0317235153/excel/images/office-toolbox-sideload.png](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/images/office-toolbox-sideload.png) | :white_check_mark:Succeeded | |

<a name="LauragraDocset0317235153%2Fexcel%2Fexcel-add-ins-get-started-angular.md"></a>
### [LauragraDocset0317235153/excel/excel-add-ins-get-started-angular.md](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/excel-add-ins-get-started-angular.md)
 - **Line 37**: **[Warning]** Invalid file link:(~/excel/img/office-toolbox-generate.png).
 - **Line 116**: **[Warning]** Invalid file link:(~/excel/img/office-toolbox-sideload.png).

<a name="LauragraDocset0317235153%2Fexcel%2Fexcel-add-ins-get-started-react.md"></a>
### [LauragraDocset0317235153/excel/excel-add-ins-get-started-react.md](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/excel-add-ins-get-started-react.md)
 - **Line 37**: **[Warning]** Invalid file link:(~/excel/img/office-toolbox-generate.png).
 - **Line 121**: **[Warning]** Invalid file link:(~/excel/img/office-toolbox-sideload.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C6%5Ca4c6380f-df62-8d13-c02d-8f00bb185ee7%5CPullRequest%5C201709062210507960-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[LauragraDocset0317235153/excel/OLD/excel-add-ins-get-started-angular.md](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/OLD/excel-add-ins-get-started-angular.md) | :white_check_mark:Succeeded | |
[LauragraDocset0317235153/excel/OLD/excel-add-ins-get-started-react.md](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/OLD/excel-add-ins-get-started-react.md) | :white_check_mark:Succeeded | |
[LauragraDocset0317235153/excel/OLD/images/excel-online-upload.png](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/OLD/images/excel-online-upload.png) | :white_check_mark:Succeeded | |
[LauragraDocset0317235153/excel/OLD/images/yo-office.png](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/OLD/images/yo-office.png) | :white_check_mark:Succeeded | |
[LauragraDocset0317235153/excel/excel-add-ins-get-started-angular.md](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/excel-add-ins-get-started-angular.md) | :white_check_mark:Succeeded | |
[LauragraDocset0317235153/excel/excel-add-ins-get-started-react.md](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/excel-add-ins-get-started-react.md) | :white_check_mark:Succeeded | |
[LauragraDocset0317235153/excel/images/office-toolbox-generate.png](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/images/office-toolbox-generate.png) | :white_check_mark:Succeeded | |
[LauragraDocset0317235153/excel/images/office-toolbox-sideload.png](https://github.com/Hongbo-Miao/LauragraRepo0317235153/blob/master/LauragraDocset0317235153/excel/images/office-toolbox-sideload.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C6%5Ca4c6380f-df62-8d13-c02d-8f00bb185ee7%5CPullRequest%5C201709062213309213-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@Hongbo-Miao -- as we discussed during yesterday's standup, we will not be mentioning Office Toolbox in any of the docs for Ignite.  We may update the quickstart articles in the future (to replace YO Office with Office Toolbox) if/when Office Toolbox is GA, but that will not happen before Ignite.

**Comment by kbrandl** [comment]
Since this won't be done before Ignite, I'm closing this PR.  I've saved the new versions of each get started article (and the 2 new images), so we can implement the changes (to reference Office Toolbox instead of YO Office) whenever Office Toolbox is GA (post-Ignite).

**Pull request closed without merging**
